export const RECEIVE_OPCODES = {
  0x01: 'LOGIN_PASSWORD',
};

export const SEND_OPCODES = {
};

export const CONNECTION_CONSTS = {
  UPDATE_CONNECTION: 'CONNECTION/UPDATE_CONNECTION',
  UPDATE_FAKE_PORTS: 'CONNECTION/UPDATE_FAKE_PORTS',
};

export const ACCOUNT_CONSTS = {
  UPDATE_ACCOUNT: 'ACCOUNT/UPDATE_ACCOUNT',
};
