export const RECEIVE_OPCODES = {
  0x01: 'LOGIN_PASSWORD',
};

export const SEND_OPCODES = {
  LOGIN_STATUS: 0x00,
  SERVER_LIST: 0x0A,
};

export const LOGIN_RESPONSE = {
  BLOCKED: 3,
  WRONG_PASSWORD: 4,
  LOGIN_NOT_FOUND: 5,
  SYSTEM_FAILURE: 6,
  ALREADY_LOGGED_IN: 7,
  CONNECTION_LIMIT_EXCEEDED: 10,
  AGE_LIMITATION: 11,
  GM_IP_RESTRICT: 13,
  GATEWAY_ERROR: 14,
  LOGIN_PROCESSING: 15,
  EMAIL_NOT_VERIFIED: 16,
  TOS: 23,
  REQUEST_DOWNLOAD: 27,
};
